[build]
  command = "pip install -r requirements.txt"
  functions = "functions"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.12"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 