[build]
  command = "apt-get update && apt-get install -y build-essential libatlas-base-dev gfortran && pip install -r requirements.txt"
  functions = "functions"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 